---
title: "logistic Regression"
author: "Samyukta Reddy"
date: "4/15/2021"
output: word_document
---

```{r}
setwd("C:/Users/rvogg/Desktop/project")

set.seed(1)
df <- read.csv(file = "training_sample.csv",header = TRUE)
head(df,3)
```


```{r}

ind <- sample(dim(df)[1], dim(df)[1]*0.8) # 80-20 training-testing data split 

train <- df[ind,]
test <- df[-ind,]

```



```{r}
ordered_glm <- glm(ordered~basket_icon_click+basket_add_list+basket_add_detail+account_page_click+promo_banner_click+detail_wishlist_add+saw_checkout+saw_homepage+device_mobile+device_tablet+loc_uk+device_mobile+device_computer+device_tablet, family = binomial,data = train)

summary(ordered_glm)

# prediction is done on testing data

pred_glm <- predict(ordered_glm,newdata=test, type = "response")

probs_glm <- ifelse(pred_glm > 0.5, "1","0" ) # "up","down"

ordered_test <- test$ordered

tab <- table(probs_glm,ordered_test)

tab

```

```{r}
library(caret)
confusionMatrix(tab)
```
*******

with having factors but the accuracy remains same.

```{r}
col_names <- names(df)[-1]
df[,col_names] <- lapply(df[,col_names] , factor)
summary(df)
```

```{r}
glm_factor <- glm(ordered~basket_icon_click+basket_add_list+basket_add_detail+account_page_click+promo_banner_click+detail_wishlist_add+saw_checkout+saw_homepage+device_mobile+device_tablet+loc_uk+device_mobile+device_computer+device_tablet, family = binomial,data = train)

summary(glm_factor)

pred_glm <- predict(ordered_glm,newdata=test, type = "response")

probs_glm <- ifelse(pred_glm > 0.5, "1","0" ) # "up","down"

ordered_test <- test$ordered

tab <- table(probs_glm,ordered_test)

tab

confusionMatrix(tab)

```